# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      # pwsh exit with 0 even if ReadLine made errors, the 1+ code is special for an example as parser error
      # So testing here with the "silentness"
      - pwsh --File src/test-all.ps1 2>&1 | wc --bytes | grep -Fxq '0'
  fmt:
    cmds:
      - dprint fmt
      - nixpkgs-fmt ./*.nix
      - pwsh -File ./tools/lint-fix.ps1
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - nixpkgs-fmt --check ./*.nix
  repl:
    cmds:
      - pwsh -NoExit -File src/repl.ps1
  setup:
    cmds:
      - pwsh --Command 'Install-Module -Name PSScriptAnalyzer -Force'
  deps:
    cmds:
      - pwsh -File ./tools/deps.ps1
