# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      # pwsh exit with 0 even if ReadLine made errors, the 1+ code is special for an example as parser error
      # So testing here with the "silentness"
      - pwsh --File test-all.ps1 2>&1 | wc --bytes | grep -Fxq '0'
  fmt:
    cmds:
      - dprint fmt
      - nixpkgs-fmt ./*.nix
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - nixpkgs-fmt --check ./*.nix
  deps:
    cmds:
      - nix --version
      - nil --version
      - task --version
      - dprint --version
      - typos --version
      - pwsh --version
      - grep --version
      - wc --version
