# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      # pwsh exit with 0 even if ReadLine made errors, the 1+ code is special for an example as parser error
      # So returns 1+ with the result by yourself in each cmd
      - pwsh --File ./tools/test-all.ps1
      - pwsh --Command 'Test-ModuleManifest -Path *.psd1'
  fmt:
    cmds:
      - dprint fmt
      - nixpkgs-fmt ./*.nix
      - pwsh -File ./tools/lint-fix.ps1
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - nixpkgs-fmt --check ./*.nix
  repl:
    cmds:
      - pwsh -NoExit -File ./tools/repl.ps1
  setup:
    cmds:
      - pwsh -File ./tools/setup.ps1
  bench:
    cmds:
      - pwsh -File ./tools/benchmark.ps1
  deps:
    cmds:
      - pwsh -File ./tools/deps.ps1
  help:
    cmds:
      - task --list-all
